### ISSUE TITLE
Support Basic Authentication

### ISSUE THREAD

**Issue by gunzip** [raviqqe/muffet#33] opened 2018-05-08 07:02 UTC
Is there any way to use basic authentication ie. muffet https://user:pass@example.com ?

**Comment by gunzip** [comment] 2018-05-08 17:40
mm in which sense ? I'd like to use muffet in a test website which is password protected so
`muffet https://user:pass@example.com` would be a good fit : )

**Comment by raviqqe** [comment] 2018-05-09 06:49
The problem is that `muffet` tries to scrape all pages in the same domain. If we add the feature, it must set authentication headers individually for each page as it's common to have multiple pages which are protected and dedicated for users like `https://foo.com/<username>/. Do you want to

**Comment by gunzip** [comment] 2018-05-09 07:46
> do you want to check links on something like private websites which are accessible only to some companies or communities

exactly, I've a pre-production website which is password protected and Iìd like to check links before going public.

**Comment by raviqqe** [comment] 2018-05-15 01:10
Closed by 8a36692. Thanks for your contribution!

**Closed by raviqqe** 2018-05-15 01:10 UTC
Labels: enhancement
