### ISSUE TITLE
Feature Request: Export/results as JSON

### ISSUE THREAD

**Issue by ssx** [raviqqe/muffet#43] opened 2018-12-05 10:13 UTC
As the title states, would it be possible to get the resultset as JSON?

**Comment by raviqqe** [comment] 2018-12-06 06:51
Can you describe some concrete use case fo the feature?

**Comment by ssx** [comment] 2018-12-06 07:43
Hi @raviqqe!

Certainly! I was planning to use muffet programmatically to automatically scan through and collect results on link statuses then do some further processing after that point - at present to parse the output of muffet is a little clunky, so with JSON it would make it a lot easier to integrate and manipulate for various systems.

**Comment by raviqqe** [comment] 2018-12-10 01:00
Do you want output in stream or just batch? I don't still understand how you want to process the output data. Will it be combined with other stream data?

**Comment by anapaulagomes** [comment] 2020-03-23 07:34
I could use this feature. I have to write a report about the availability of certain website and this feature would be helpful in this task.

**Comment by raviqqe** [comment] 2020-09-23 19:19
Do you want JSON lines or a JSON array for results?

**Comment by ssx** [comment] 2020-09-23 19:21
I think array would be most useful

**Comment by raviqqe** [comment] 2020-09-27 19:42
I'm thinking a minimal output format in JSON omitting successful ones as they would be useless for the linting purpose. How about this?

```json
[
  {
    "url": "http://foo.com",
    "errors": [
      "url": "http://foo.com/foo",
      "error": "404"
    ]
  }
  , ...
]
```

**Comment by ssx** [comment] 2020-09-27 19:56
That works for me. You could even group the errors by code perhaps too.

Scott

**Comment by raviqqe** [comment] 2020-09-27 20:14
Thanks for your quick reply!

> You could even group the errors by code perhaps too.

The problem is that the errors can be any strings that are potentially long because they are not only from the HTTP layer but can be from lower layers like TCP or even DNS. I'll keep them in a message.

I'll use the first format as the second one is not friendly with some languages' type systems and protocols

**Comment by ssx** [comment] 2020-09-27 20:16
Ah yes, that definitely makes sense then!

**Comment by raviqqe** [comment] 2020-09-27 20:49
Merged into master.

**Closed** 2020-09-27 20:49 UTC
Labels: enhancement
